# Generated by Django 4.2.1 on 2024-07-23 18:32

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0019_rename_amount_to_withhold_calculation_data_results_amount_to_withhold_child1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='allocation_method_for_arrears',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='garcalculation_data',
            name='allocation_method_for_garnishment',
        ),
    ]
