# Generated by Django 4.2.1 on 2024-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0020_rename_allocation_method_for_arrears_garcalculation_data_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_details',
            old_name='state_taxes',
            new_name='state_tax',
        ),
    ]
